-- MySQL Script generated by MySQL Workbench
-- vie 05 jul 2019 23:23:40 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_amordecristo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_amordecristo` ;

-- -----------------------------------------------------
-- Schema db_amordecristo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_amordecristo` DEFAULT CHARACTER SET utf8 ;
USE `db_amordecristo` ;

-- -----------------------------------------------------
-- Table `db_amordecristo`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_amordecristo`.`users` ;

CREATE TABLE IF NOT EXISTS `db_amordecristo`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `surname` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(200) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_amordecristo`.`nets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_amordecristo`.`nets` ;

CREATE TABLE IF NOT EXISTS `db_amordecristo`.`nets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `parent_netId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nets_nets1_idx` (`parent_netId` ASC),
  CONSTRAINT `fk_nets_nets1`
    FOREIGN KEY (`parent_netId`)
    REFERENCES `db_amordecristo`.`nets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_amordecristo`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_amordecristo`.`groups` ;

CREATE TABLE IF NOT EXISTS `db_amordecristo`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `netId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_groups_nets1_idx` (`netId` ASC),
  CONSTRAINT `fk_groups_nets1`
    FOREIGN KEY (`netId`)
    REFERENCES `db_amordecristo`.`nets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_amordecristo`.`groups_has_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_amordecristo`.`groups_has_users` ;

CREATE TABLE IF NOT EXISTS `db_amordecristo`.`groups_has_users` (
  `groupId` INT NOT NULL,
  `userId` INT NOT NULL,
  `type` ENUM('Lider', 'Columna', 'Miembro') NOT NULL,
  PRIMARY KEY (`groupId`, `userId`),
  INDEX `fk_groups_has_users_users1_idx` (`userId` ASC),
  INDEX `fk_groups_has_users_groups_idx` (`groupId` ASC),
  CONSTRAINT `fk_groups_has_users_groups`
    FOREIGN KEY (`groupId`)
    REFERENCES `db_amordecristo`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groups_has_users_users1`
    FOREIGN KEY (`userId`)
    REFERENCES `db_amordecristo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_amordecristo`.`net_leaders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_amordecristo`.`net_leaders` ;

CREATE TABLE IF NOT EXISTS `db_amordecristo`.`net_leaders` (
  `netId` INT NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`netId`, `userId`),
  INDEX `fk_nets_has_users_users1_idx` (`userId` ASC),
  INDEX `fk_nets_has_users_nets1_idx` (`netId` ASC),
  CONSTRAINT `fk_nets_has_users_nets1`
    FOREIGN KEY (`netId`)
    REFERENCES `db_amordecristo`.`nets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nets_has_users_users1`
    FOREIGN KEY (`userId`)
    REFERENCES `db_amordecristo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_amordecristo`.`departaments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_amordecristo`.`departaments` ;

CREATE TABLE IF NOT EXISTS `db_amordecristo`.`departaments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` mediumtext NOT NULL,
  `slogan` VARCHAR(140) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_amordecristo`.`departament_leaders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_amordecristo`.`departament_leaders` ;

CREATE TABLE IF NOT EXISTS `db_amordecristo`.`departament_leaders` (
  `departamentId` INT NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`departamentId`, `userId`),
  INDEX `fk_departaments_has_users_users1_idx` (`userId` ASC),
  INDEX `fk_departaments_has_users_departaments1_idx` (`departamentId` ASC),
  CONSTRAINT `fk_departaments_has_users_departaments1`
    FOREIGN KEY (`departamentId`)
    REFERENCES `db_amordecristo`.`departaments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departaments_has_users_users1`
    FOREIGN KEY (`userId`)
    REFERENCES `db_amordecristo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_amordecristo`.`licenses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_amordecristo`.`licenses` ;

CREATE TABLE IF NOT EXISTS `db_amordecristo`.`licenses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_amordecristo`.`reports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_amordecristo`.`reports` ;

CREATE TABLE IF NOT EXISTS `db_amordecristo`.`reports` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `offering` INT NOT NULL,
  `comment_leaders` TEXT NULL,
  `comment_leaders_net` TEXT NULL,
  `spiritual_work` VARCHAR(100) NOT NULL,
  `date_spiritual` DATETIME NOT NULL,
  `groupId` INT NOT NULL,
  `userId1` INT NOT NULL,
  `userId2` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reports_groups1_idx` (`groupId` ASC),
  INDEX `fk_reports_users1_idx` (`userId1` ASC),
  INDEX `fk_reports_users2_idx` (`userId2` ASC),
  CONSTRAINT `fk_reports_groups1`
    FOREIGN KEY (`groupId`)
    REFERENCES `db_amordecristo`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reports_users1`
    FOREIGN KEY (`userId1`)
    REFERENCES `db_amordecristo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reports_users2`
    FOREIGN KEY (`userId2`)
    REFERENCES `db_amordecristo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_amordecristo`.`let_mep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_amordecristo`.`let_mep` ;

CREATE TABLE IF NOT EXISTS `db_amordecristo`.`let_mep` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reason` VARCHAR(45) NOT NULL,
  `reportId` INT NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_let_mep_reports1_idx` (`reportId` ASC),
  INDEX `fk_let_mep_users1_idx` (`userId` ASC),
  CONSTRAINT `fk_let_mep_reports1`
    FOREIGN KEY (`reportId`)
    REFERENCES `db_amordecristo`.`reports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_let_mep_users1`
    FOREIGN KEY (`userId`)
    REFERENCES `db_amordecristo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_amordecristo`.`report_consolidation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_amordecristo`.`report_consolidation` ;

CREATE TABLE IF NOT EXISTS `db_amordecristo`.`report_consolidation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reportId` INT NOT NULL,
  `userId` INT NOT NULL,
  `visited` TINYINT(1) NULL,
  `consolidated` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_report_consolidation_reports1_idx` (`reportId` ASC),
  INDEX `fk_report_consolidation_users1_idx` (`userId` ASC),
  CONSTRAINT `fk_report_consolidation_reports1`
    FOREIGN KEY (`reportId`)
    REFERENCES `db_amordecristo`.`reports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_consolidation_users1`
    FOREIGN KEY (`userId`)
    REFERENCES `db_amordecristo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_amordecristo`.`let_consolidation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_amordecristo`.`let_consolidation` ;

CREATE TABLE IF NOT EXISTS `db_amordecristo`.`let_consolidation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reason` VARCHAR(250) NOT NULL,
  `reportId` INT NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_let_consolidation_reports1_idx` (`reportId` ASC),
  INDEX `fk_let_consolidation_users1_idx` (`userId` ASC),
  CONSTRAINT `fk_let_consolidation_reports1`
    FOREIGN KEY (`reportId`)
    REFERENCES `db_amordecristo`.`reports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_let_consolidation_users1`
    FOREIGN KEY (`userId`)
    REFERENCES `db_amordecristo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_amordecristo`.`let_spiritual`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_amordecristo`.`let_spiritual` ;

CREATE TABLE IF NOT EXISTS `db_amordecristo`.`let_spiritual` (
  `id` INT NOT NULL,
  `reason` VARCHAR(250) NOT NULL,
  `reportId` INT NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_let_spiritual_reports1_idx` (`reportId` ASC),
  INDEX `fk_let_spiritual_users1_idx` (`userId` ASC),
  CONSTRAINT `fk_let_spiritual_reports1`
    FOREIGN KEY (`reportId`)
    REFERENCES `db_amordecristo`.`reports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_let_spiritual_users1`
    FOREIGN KEY (`userId`)
    REFERENCES `db_amordecristo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_amordecristo`.`let_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_amordecristo`.`let_group` ;

CREATE TABLE IF NOT EXISTS `db_amordecristo`.`let_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reason` VARCHAR(250) NOT NULL,
  `reportId` INT NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_let_group_reports1_idx` (`reportId` ASC),
  INDEX `fk_let_group_users1_idx` (`userId` ASC),
  CONSTRAINT `fk_let_group_reports1`
    FOREIGN KEY (`reportId`)
    REFERENCES `db_amordecristo`.`reports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_let_group_users1`
    FOREIGN KEY (`userId`)
    REFERENCES `db_amordecristo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_amordecristo`.`go_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_amordecristo`.`go_group` ;

CREATE TABLE IF NOT EXISTS `db_amordecristo`.`go_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reconciled` TINYINT(1) NULL,
  `converted` TINYINT(1) NULL,
  `reportId` INT NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_go_group_reports1_idx` (`reportId` ASC),
  INDEX `fk_go_group_users1_idx` (`userId` ASC),
  CONSTRAINT `fk_go_group_reports1`
    FOREIGN KEY (`reportId`)
    REFERENCES `db_amordecristo`.`reports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_go_group_users1`
    FOREIGN KEY (`userId`)
    REFERENCES `db_amordecristo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_amordecristo`.`privileges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_amordecristo`.`privileges` ;

CREATE TABLE IF NOT EXISTS `db_amordecristo`.`privileges` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `privilege` VARCHAR(100) NOT NULL,
  `reportId` INT NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_privileges_reports1_idx` (`reportId` ASC),
  INDEX `fk_privileges_users1_idx` (`userId` ASC),
  CONSTRAINT `fk_privileges_reports1`
    FOREIGN KEY (`reportId`)
    REFERENCES `db_amordecristo`.`reports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_privileges_users1`
    FOREIGN KEY (`userId`)
    REFERENCES `db_amordecristo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_amordecristo`.`let_church`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_amordecristo`.`let_church` ;

CREATE TABLE IF NOT EXISTS `db_amordecristo`.`let_church` (
  `id` INT NOT NULL,
  `reason` VARCHAR(100) NOT NULL,
  `reportId` INT NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_let_church_reports1_idx` (`reportId` ASC),
  INDEX `fk_let_church_users1_idx` (`userId` ASC),
  CONSTRAINT `fk_let_church_reports1`
    FOREIGN KEY (`reportId`)
    REFERENCES `db_amordecristo`.`reports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_let_church_users1`
    FOREIGN KEY (`userId`)
    REFERENCES `db_amordecristo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_amordecristo`.`go_church`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_amordecristo`.`go_church` ;

CREATE TABLE IF NOT EXISTS `db_amordecristo`.`go_church` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `friday` TINYINT(1) NULL,
  `sunday` TINYINT(1) NULL,
  `young` TINYINT(1) NULL,
  `reportId` INT NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_go_church_reports1_idx` (`reportId` ASC),
  INDEX `fk_go_church_users1_idx` (`userId` ASC),
  CONSTRAINT `fk_go_church_reports1`
    FOREIGN KEY (`reportId`)
    REFERENCES `db_amordecristo`.`reports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_go_church_users1`
    FOREIGN KEY (`userId`)
    REFERENCES `db_amordecristo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_amordecristo`.`users_has_licenses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_amordecristo`.`users_has_licenses` ;

CREATE TABLE IF NOT EXISTS `db_amordecristo`.`users_has_licenses` (
  `users_id` INT NOT NULL,
  `licenses_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `licenses_id`),
  INDEX `fk_users_has_licenses_licenses1_idx` (`licenses_id` ASC),
  INDEX `fk_users_has_licenses_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_licenses_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `db_amordecristo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_licenses_licenses1`
    FOREIGN KEY (`licenses_id`)
    REFERENCES `db_amordecristo`.`licenses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
