FORMAT: 1A

# Amor De Cristo API


# Group Grupos

## Coleccion de grupos [/groups]

### Lista todos los grupos [GET]

+ Response 200 (application/json)

		[
			{
				id: 1,
				name: "Jovenes de reto",
				netId: 1,
				workTeam: [
					{
						userId: 1,
						type: "Lider"
					},
					{
						userId: 2,
						type: "Lider"
					},
					{
						userId: 3,
						type: "Columna"
					}
				]
			}
		]

## Crear grupo [/group]

### Crear un nuevo grupo [POST]
Se crea un nuevo grupo dentro de una red sin asignacion de equipo de trabajo enviando el nombre y el id de la red a la que pertenece.

+ Request JSON Message

    + Headers

            Accept: application/json

    + Body
    
    		{
    			name: "Nombre del nuevo grupo",
    			netId: 2
    		}

+ Response 200 (application/json)

		[
			{
				id: 2,
				name: "Nombre del nuevo grupo",
				netId: 2,
			}
		]